name: DisplayShopAddon64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.displayshopaddon64.DisplayShopAddon64
api-version: 1.17
depend: [DisplayShops, Vault, Rep64]
commands:
  testshop:
    description: Main command for DisplayShopAddon64
  buy:
    description: Alternate commands for DisplayShopAddon64
    aliases: [sell]
permissions:
  displayshopaddon64.player:
    description: Ability to use /testshop, /buy, & /sell
    default: true
  displayshopaddon64.admin:
    description: Ability to use __________
    default: op