name: DisplayShopAddon64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.displayshopaddon64.DisplayShopAddon64
api-version: 1.17
depend: [DisplayShops, Vault, Rep64]
softdepend: [ShopGUIPlus]
commands:
  shop:
    description: Search shops for <material>/<enchant>/<player>/etc.
  buy:
    description: Search shops for <material>/<enchant>/<player>/etc.
  sell:
    description: Search shops for <material>/<enchant>/<player>/etc.
  sellgui:
    description: Open a GUI and sell items for a minimum of $<#> for each item
    aliases: [sellg, sg, sellinv, sellhand, sellall]
  shopadmin:
    description: Admin commands for DisplayShopAddon64
permissions:
  displayshopaddon64.player:
    description: Ability to use player commands
    default: true
  displayshopaddon64.player.money-move:
    description: Ability to store money into shops with command
    default: true
  displayshopaddon64.player.store-inv:
    description: Ability to store inv items into shops with command
    default: true
  displayshopaddon64.player.sell-inv:
    description: Ability to sell inv items with command
    default: true
  displayshopaddon64.player.sell-gui:
    description: Ability to open sell GUI with command
    default: true
  displayshopaddon64.admin:
    description: Ability to use admin commands
    default: op